# Generated by Django 4.2.2 on 2023-06-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaveEuromilhoes',
            new_name='Chave',
        ),
        migrations.RenameField(
            model_name='chave',
            old_name='datahora',
            new_name='data',
        ),
    ]
